<?php return array (
  'sans-serif' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'times' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'times-roman' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'courier' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'helvetica' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'zapfdingbats' => array(
    'normal' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold' => $rootDir . '/lib/fonts/ZapfDingbats',
    'italic' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold_italic' => $rootDir . '/lib/fonts/ZapfDingbats',
  ),
  'symbol' => array(
    'normal' => $rootDir . '/lib/fonts/Symbol',
    'bold' => $rootDir . '/lib/fonts/Symbol',
    'italic' => $rootDir . '/lib/fonts/Symbol',
    'bold_italic' => $rootDir . '/lib/fonts/Symbol',
  ),
  'serif' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'monospace' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'fixed' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'dejavu sans' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSans-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSans-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSans-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSans',
  ),
  'dejavu sans mono' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSansMono-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSansMono-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSansMono-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSansMono',
  ),
  'dejavu serif' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSerif-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSerif-BoldItalic',
    'italic' => $rootDir . '/lib/fonts/DejaVuSerif-Italic',
    'normal' => $rootDir . '/lib/fonts/DejaVuSerif',
  ),
  'poppins' => array(
    '100_italic' => $fontDir . '/poppins_100_italic_3e6bdece1ffacb38688171766be0924b',
    '200_italic' => $fontDir . '/poppins_200_italic_85ed0ce6f3d82fc16178616514c92f10',
    '300_italic' => $fontDir . '/poppins_300_italic_d20894f03ac9fb76641cc9c969d0525e',
    'italic' => $fontDir . '/poppins_italic_1d694924317a4790716336eefe6b364c',
    '500_italic' => $fontDir . '/poppins_500_italic_88b88e7ee0fd98a6547d793755458e47',
    '600_italic' => $fontDir . '/poppins_600_italic_342424595c018d9856448831a8da64fe',
    'bold_italic' => $fontDir . '/poppins_bold_italic_53d5a4d61eda510ddc454fa1cb2e05ef',
    '800_italic' => $fontDir . '/poppins_800_italic_688f227e413e15abe9efb5cbc2c4a863',
    '900_italic' => $fontDir . '/poppins_900_italic_46ff3439431035c93b16d7a06ec46f2b',
    '100' => $fontDir . '/poppins_100_69a32ecebae5a72c6c9df7538fc2eb96',
    '200' => $fontDir . '/poppins_200_28530177d91bd4ba08b7ffc07cebf559',
    '300' => $fontDir . '/poppins_300_fdf63d9f742346a5ee6b70f5a8af6c01',
    'normal' => $fontDir . '/poppins_normal_c1b7381dfaadf37a84cf14d786076e6d',
    '500' => $fontDir . '/poppins_500_3ab22c79a50a7416f996a1aba688428d',
    '600' => $fontDir . '/poppins_600_270e18a84ac8b306c8f31abe1d0720fa',
    'bold' => $fontDir . '/poppins_bold_7eb29046bc7eaf66b896ec27702d038b',
    '800' => $fontDir . '/poppins_800_536163191f53b5da319f92ee38a84645',
    '900' => $fontDir . '/poppins_900_2cd47d9ee4ef8f23390bc44c05a7b082',
  ),
) ?>